// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgUZ_DSI8tKSLTOzYxqApIKMN6wG3Nn0M',
    appId: '1:645325700593:web:dde37607969c47b1339850',
    messagingSenderId: '645325700593',
    projectId: 'ez2gether-58514',
    authDomain: 'ez2gether-58514.firebaseapp.com',
    storageBucket: 'ez2gether-58514.appspot.com',
    measurementId: 'G-9LPXS3KKRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVrOu1DjKVF2tWm8huks1KHEtD7u1RQnQ',
    appId: '1:645325700593:android:6b54a8c8fce9b0c9339850',
    messagingSenderId: '645325700593',
    projectId: 'ez2gether-58514',
    storageBucket: 'ez2gether-58514.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlDhyNeQBOs7ytsZJQTvIVTP18zt98Y_4',
    appId: '1:645325700593:ios:2a0d10e41b67e7f7339850',
    messagingSenderId: '645325700593',
    projectId: 'ez2gether-58514',
    storageBucket: 'ez2gether-58514.appspot.com',
    iosClientId: '645325700593-sbi9tl8q9p81ipmp6olpkrvedbap6n7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.ez2gether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlDhyNeQBOs7ytsZJQTvIVTP18zt98Y_4',
    appId: '1:645325700593:ios:ed191d30ce745bb8339850',
    messagingSenderId: '645325700593',
    projectId: 'ez2gether-58514',
    storageBucket: 'ez2gether-58514.appspot.com',
    iosClientId: '645325700593-lo4g5pcc5g5qr3ea019kclqqpo3r0c1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.ez2gether.RunnerTests',
  );
}
